### ISSUE TITLE
gnucsator compiling problem

### ISSUE THREAD

**Issue by Wojtek010265** [Qucs/gnucsator#15] opened 2024-04-07 16:54 UTC
i try to compile gnucsator. have installed prerequisites (and newest gnucap which compiled without problems) as stated in installation guide but getting error during compilation stating that e_va.h file is missing. tried to fing info about that file on the net but failed. what should i do? i use ubuntu 20-04.6 lts.

**Comment by felix-salfelder** [comment] 2024-04-07 19:50
On Sun, Apr 07, 2024 at 09:54:52AM -0700, Wojtek010265 wrote:
> e_va.h file is missing.

Thanks for letting me know, it should be fixed in develop.

The header (from modelgen-verilog) is not actually used, the include
just got in there accidentally.

**Comment by Wojtek010265** [comment] 2024-04-09 08:54
well, i tried to solve problem by commenting out #include e_va.h in file d_spembed.cc but got more error messages and compilation was unsuccessful. include screenshot
![screenshot_2024-04-09_10-47-41](https://github.com/Qucs/gnucsator/assets/133814166/a82b36be-9bfd-46c5-a359-4ebe83ed01ba)

**Comment by felix-salfelder** [comment] 2024-04-09 09:20
On Tue, Apr 09, 2024 at 01:54:38AM -0700, Wojtek010265 wrote:
> well, i tried to solve problem by commenting out #include e_va.h in file
> d_spembed.cc but got more error messages and compilation was unsuccessful.
> include screenshot
> ![screenshot_2024-04-09_10-47-41](https://github.com/Qucs/gnucsator/assets/133814166/a82b36be-9bfd-46c5-a359-4ebe83ed01ba)

Thanks for retrying.

Some flags are missing in your screenshot. Perhaps there's a stale
makefile involved, as things have changed a bit recently..
From a fresh clone I get this:

$ git log -1
commit af62b049f666865af177e5c0f8a959aef8fbe298 [..]
$ ./configure
sub_makefile include/Makefile
sub_makefile qucsator/Makefile
sub_makefile contrib/Makefile
sub_configure tests
prefix: /usr/local
pkglibdir: /usr/local/lib/gnucap
plugpath: /usr/local/lib/gnucap
$ make
asking /usr/local/bin/gnucap-conf
[ -e Make2 ] || echo "# here you may override settings\n#CPPFLAGS = -DDO_TRACE -DTRACE_UNTESTED\n#CXXFLAGS = -O0 -g3" > Make2
asking /usr/local/bin/gnucap-conf
for i in qucsator include contrib; do \
  make -C ${i} all; \
done
make[1]: Entering directory '/tmp/gnucap-qucs/qucsator'
g++ -I/usr/local/include/gnucap  -I../qucsator   -c ../qucsator/microstrip/mscoupled.cpp -fPIC -o mscoupled.o # qucsator/Make1
[..]

In particular, -I/usr/local/include/gnucap is passed. I wonder why it's missing
on your end. It should have come from gnucap-conf. Can you reproduce

$ which gnucap-conf
/usr/local/bin/gnucap-conf
$ gnucap-conf --cppflags
-I/usr/local/include/gnucap

on your system?

**Comment by felix-salfelder** [comment] 2024-10-31 17:17
Still cannot reproduce. Please reopen as needed.

**Closed as completed by felix-salfelder** 2024-10-31 17:17 UTC
